### ISSUE TITLE
crash on linux

### ISSUE THREAD

**Issue by sneekee-stache** [G3rste/wolftaming#12]
game crash with the mod on linux
the only thing i have installed to try it is the base game with petIA and wolf taming
here is the log:https://pastebin.com/Rr4RVsJH

**Comment by G3rste** [comment]
Does [this](https://github.com/G3rste/petai/files/8199940/petai.zip) fix your issue?

**Comment by sneekee-stache** [comment]
it did work with this petAI
thank you

**Comment by G3rste** [comment]
Thanks for the quick test. I released a new version containing this patch.
